#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J particle-pthreads16
#SBATCH -o particle-pthreads16.stdout
#SBATCH -n 16         
#SBATCH -p normal
#SBATCH -t 00:10:00     
./pthreads -p 16 -n 1000 -o pthreads.txt
